# NumPy 

* NumPy is a Python library used for working with arrays.
* It also has functions for working in domain of linear algebra, fourier transform, and matrices.
* NumPy stands for Numerical Python.

## Why Use NumPy?

* In Python we have lists that serve the purpose of arrays, but they are slow to process.

* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* Arrays are very frequently used in data science, where speed and resources are very important

# Why is NumPy Faster Than Lists?

* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

* This behavior is called locality of reference in computer science.

* This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



In [1]:
!pip install numpy

In [2]:
import numpy as np;

In [3]:
# creating an array using numpy

array=np.array([1,2,3,4,5]);

print("\nType of array is {}".format(type(array)))

print("\nDimension of array is {}".format(array.ndim))

print ("\nDatatype of array is {}".format(array.dtype))

print("\n{}".format(array))

print("\nLast element in array is {}".format(array[-1]))

print ("\nFirst Element in array is {}".format(array[0]))


Type of array is <class 'numpy.ndarray'>

Dimension of array is 1

Datatype of array is int64

[1 2 3 4 5]

Last element in array is 5

First Element in array is 1


In [4]:
# Specifying the data types while creating array

array = np.array([1, 2, 3, 4], dtype='S')

print("\nType of array is {}".format(type(array)))

print("\nDimension of array is {}".format(array.ndim))

print ("\nDatatype of array is {}".format(array.dtype))

print("\n{}".format(array))



Type of array is <class 'numpy.ndarray'>

Dimension of array is 1

Datatype of array is |S1

[b'1' b'2' b'3' b'4']


In [5]:
array2D=np.array([[1,2,3],[2,3,2],[3,4,2]])

print("\nType of array is {}".format(type(array2D)))

print("\nDimension of array is {}".format(array2D.ndim))

print ("\nDatatype of array is {}".format(array2D.dtype))

print("\n{}".format(array2D))


Type of array is <class 'numpy.ndarray'>

Dimension of array is 2

Datatype of array is int64

[[1 2 3]
 [2 3 2]
 [3 4 2]]


## Array Slicing

In [6]:
print(array[0:3])

[b'1' b'2' b'3']


In [7]:
print(array[-3:-1])

[b'2' b'3']


In [8]:
print(array2D[0:2,1])

[2 3]


In [9]:
print (array2D[0,1:2])

[2]


# Copy and View

## Copy
* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [10]:
a=np.arange(15)
aCopy=a.copy()
aCopy[0]=2
print(a)
print(aCopy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## View

* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [11]:
a=np.arange(15)
a1=a.view()
a1[0]=2
print(aCopy)
print(a)

[ 2  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Zero Array

In [12]:
zero=np.zeros((3, 3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Unit Matrix 

In [13]:
identity=np.ones((3,3))
print (identity)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Matrix with same value

In [14]:

print(np.full((5, 3), 3))

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


#### Identity Matrix

In [15]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Diagonal Matrix

In [16]:
print(np.diag([2, 5, 10, 15]))

[[ 2  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


# Random Numbers in NumPy

In [17]:
# To get the random Numbers
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.7580470193576555
0.5570842134504843
0.43375411349563686
0.5224416095601241
0.33996254463772646


#### Seed 
* To generate a random numbers with in range

In [18]:
np.random.seed(10)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.771320643266746
0.0207519493594015
0.6336482349262754
0.7488038825386119
0.4985070123025904


In [19]:
# you can specify the shape
x = np.random.random((5, 3))
print(x)

[[0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982]
 [0.95339335 0.00394827 0.51219226]
 [0.81262096 0.61252607 0.72175532]
 [0.29187607 0.91777412 0.71457578]]


#### Random Int

In [20]:
print(np.random.randint(low=10,high=100))
print(np.random.randint(low=10,high=100,size=10))
print(np.random.randint(low=10,high=100,size=(3,3)))

23
[35 23 96 40 40 99 22 75 41 67]
[[46 37 28]
 [87 32 33]
 [21 38 84]]


**Round function**

In [21]:
x=np.random.random((2,2))
print("Before Round Function \n {}".format(x))   
x=np.round(x,2)
x=x*10
print ("\nUsing Round rounding the decimal value upto 2 digits \n{}".format(x))

Before Round Function 
 [[0.31923609 0.09045935]
 [0.30070006 0.11398436]]

Using Round rounding the decimal value upto 2 digits 
[[3.2 0.9]
 [3.  1.1]]


**Changing the datatype**

In [22]:
x.astype(int)
print(x)
## Check Why its not working properly

[[3.2 0.9]
 [3.  1.1]]


**Reshape**

* This can be used to change the dimension of array

In [23]:
sample=np.arange(100)
print (sample);

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [24]:
sample=sample.reshape(5,20)

In [25]:
print(sample)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [26]:
sample.shape

(5, 20)

In [27]:
# 10 rows and not sure about how many columns will be there
sample.reshape(10,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Mathematical function in numpy

## Simple Airthmetic

In [28]:
a1=np.arange(10,100,10)
a2=np.arange(1,10,1)
print ("Array 1 is {}".format(a1))
print ("\nArray 2 is {}".format(a2))
# Add
print("\nAddition is {}".format(np.add(a1,a2)))

#Subtract
print("\nSubtraction is {}".format(np.subtract(a1,a2)))

#Multiplication
print("\nMultiplication is {}".format(np.multiply(a1,a2)))

#Division
print("\nDivision is {}".format(np.divide(a1,a2)))

#power
print("\nPower is {}".format(np.power(a1,a2)))

#mod
print("\nModulus is {}".format(np.mod(a1,a2)))

#remainder Same as mod
print("\nRemainder is {}".format(np.remainder(a1,a2)))

#Quotient and mod
print("\nQuotient and mod is {}".format(np.divmod(a1,a2)))

Array 1 is [10 20 30 40 50 60 70 80 90]

Array 2 is [1 2 3 4 5 6 7 8 9]

Addition is [11 22 33 44 55 66 77 88 99]

Subtraction is [ 9 18 27 36 45 54 63 72 81]

Multiplication is [ 10  40  90 160 250 360 490 640 810]

Division is [10. 10. 10. 10. 10. 10. 10. 10. 10.]

Power is [                10                400              27000
            2560000          312500000        46656000000
      8235430000000   1677721600000000 387420489000000000]

Modulus is [0 0 0 0 0 0 0 0 0]

Remainder is [0 0 0 0 0 0 0 0 0]

Quotient and mod is (array([10, 10, 10, 10, 10, 10, 10, 10, 10]), array([0, 0, 0, 0, 0, 0, 0, 0, 0]))


### Trignometric ,Log,Summation

In [29]:
x=np.arange(1,10)

print("Array is {}".format(x))

# Sin value of each element in array
print("\nSin value are {}".format(np.sin(x)))

# Cos value
print("\nCos value are {}".format(np.cos(x)))

# Tan Value of each element
print("\nTan value are {}".format(np.tan(x)))

#to get the exponential values i,e., e^num
print("\nExp value are {}".format(np.exp(x)))

#log base 2
print("\nLog Base 2 value are {}".format(np.log2(x)))

#Natural Log
print("\nNatural Log value are {}".format(np.log(x)))

#Summation
print ("\nSummation value is {}".format(np.sum(x)))

#Max Value
print("\nMaximum value is {}".format(np.max(x)))

Array is [1 2 3 4 5 6 7 8 9]

Sin value are [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]

Cos value are [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]

Tan value are [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]

Exp value are [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]

Log Base 2 value are [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]

Natural Log value are [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]

Summation value is 45

Maximum value is 9
